/* ============================================================
 * GitHub Operations
 * High-level operations: create branch, commit file, open PR.
 * Orchestrates the full submission workflow.
 * ============================================================ */

import { createOctokitClient, getGitHubConfig } from './client';
import type { SubmissionResult } from '@/utils/types';

/**
 * Creates a new branch from the base branch (main).
 */
async function createBranch(branchName: string): Promise<void> {
  const config = getGitHubConfig();
  const octokit = createOctokitClient(config);

  // Get the SHA of the base branch
  const { data: ref } = await octokit.git.getRef({
    owner: config.owner,
    repo: config.repo,
    ref: `heads/${config.baseBranch}`,
  });

  // Create the new branch
  await octokit.git.createRef({
    owner: config.owner,
    repo: config.repo,
    ref: `refs/heads/${branchName}`,
    sha: ref.object.sha,
  });
}

/**
 * Commits a file to the specified branch.
 * Creates the file if it doesn't exist, updates it if it does.
 */
async function commitFile(
  branchName: string,
  filePath: string,
  content: string,
  commitMessage: string
): Promise<void> {
  const config = getGitHubConfig();
  const octokit = createOctokitClient(config);

  // Check if file already exists (for updates)
  let existingSha: string | undefined;
  try {
    const { data } = await octokit.repos.getContent({
      owner: config.owner,
      repo: config.repo,
      path: filePath,
      ref: branchName,
    });
    if (!Array.isArray(data) && data.type === 'file') {
      existingSha = data.sha;
    }
  } catch {
    // File doesn't exist yet — that's fine
  }

  // Create or update the file
  await octokit.repos.createOrUpdateFileContents({
    owner: config.owner,
    repo: config.repo,
    path: filePath,
    message: commitMessage,
    content: Buffer.from(content).toString('base64'),
    branch: branchName,
    ...(existingSha ? { sha: existingSha } : {}),
  });
}

/**
 * Opens a Pull Request from the feature branch to the base branch.
 */
async function createPullRequest(
  branchName: string,
  title: string,
  body: string
): Promise<{ prUrl: string; prNumber: number }> {
  const config = getGitHubConfig();
  const octokit = createOctokitClient(config);

  const { data: pr } = await octokit.pulls.create({
    owner: config.owner,
    repo: config.repo,
    title,
    body,
    head: branchName,
    base: config.baseBranch,
  });

  return { prUrl: pr.html_url, prNumber: pr.number };
}

/**
 * Orchestrates the full submission workflow:
 * 1. Create feature branch
 * 2. Commit JSON file
 * 3. Open Pull Request
 *
 * @param name — Resource name (used for branch/file naming)
 * @param filePath — Path within the repo (e.g., "content/subscriptions/my-sub.json")
 * @param jsonContent — The generated JSON string
 * @returns — Submission result with PR URL or error
 */
export async function submitToGitHub(
  name: string,
  filePath: string,
  jsonContent: string
): Promise<SubmissionResult> {
  const branchName = `feature/subscription-${name.toLowerCase().replace(/\s+/g, '-')}`;
  const timestamp = Date.now();
  const uniqueBranch = `${branchName}-${timestamp}`;

  try {
    // Step 1: Create feature branch
    await createBranch(uniqueBranch);

    // Step 2: Commit JSON file
    await commitFile(
      uniqueBranch,
      filePath,
      jsonContent,
      `feat: add subscription ${name}`
    );

    // Step 3: Open Pull Request
    const { prUrl, prNumber } = await createPullRequest(
      uniqueBranch,
      `Add subscription: ${name}`,
      [
        `## New Subscription: ${name}`,
        '',
        `This PR adds a new subscription configuration.`,
        '',
        `**File:** \`${filePath}\``,
        `**Branch:** \`${uniqueBranch}\``,
        '',
        '---',
        '*Generated by TinaCMS Terraform Config Builder*',
      ].join('\n')
    );

    return {
      success: true,
      prUrl,
      prNumber,
      branchName: uniqueBranch,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error during GitHub submission';
    return {
      success: false,
      error: message,
      branchName: uniqueBranch,
    };
  }
}
